CREATE TABLE gifts(
    id SERIAL PRIMARY KEY,
    title CHARACTER VARYING(255) NOT NULL,
    giver CHARACTER VARYING(255) NOT NULL,
    receiver CHARACTER VARYING(255) NOT NULL,
    delivery_date DATE NOT NULL
);
